[package]
name = "chaoscontrol-wasm-differential"
version.workspace = true
edition.workspace = true
authors.workspace = true
license = "AGPL-3.0-or-later"

[dependencies]
blake3 = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tempfile = "3"
thiserror = "2"
wait-timeout = "0.2"
differential-execution-core = { git = "https://seed.radicle.garden/z2pbwQ4Zd52M4oC1W9bLT3nQem9ay.git", rev = "cad5a7cb6c6502b0ec5dc76c51e03352260d8efd" }

[dev-dependencies]
proptest = "1"
