[workspace]
members = [
    "crates/chaoscontrol-protocol",
    "crates/chaoscontrol-replay-evidence-core",
    "crates/chaoscontrol-sim-core",
    "crates/chaoscontrol-smr",
    "crates/chaoscontrol-sdk",
    "crates/chaoscontrol-fault",
    "crates/chaoscontrol-vmm",
    "crates/chaoscontrol-trace",
    "crates/chaoscontrol-explore",
    "crates/chaoscontrol-dashboard",
    "crates/chaoscontrol-replay",
    "crates/chaoscontrol-evidence",
    "crates/chaoscontrol-guest",
    "crates/chaoscontrol-raft-guest",
    "crates/chaoscontrol-guest-net",
    "crates/chaoscontrol-net-guest",
    "crates/chaoscontrol-redb-guest",
    "crates/chaoscontrol-rust-workload-guest",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["ChaosControl Contributors"]
license = "Apache-2.0"

[workspace.metadata.tigerstyle]
default_scope = [
    "-p",
    "chaoscontrol-protocol",
    "-p",
    "chaoscontrol-replay-evidence-core",
    "-p",
    "chaoscontrol-sim-core",
    "-p",
    "chaoscontrol-smr",
    "-p",
    "chaoscontrol-sdk",
    "-p",
    "chaoscontrol-fault",
    "-p",
    "chaoscontrol-vmm",
    "-p",
    "chaoscontrol-trace",
    "-p",
    "chaoscontrol-explore",
    "-p",
    "chaoscontrol-dashboard",
    "-p",
    "chaoscontrol-replay",
    "-p",
    "chaoscontrol-evidence",
    "-p",
    "chaoscontrol-guest",
    "-p",
    "chaoscontrol-raft-guest",
    "-p",
    "chaoscontrol-guest-net",
    "-p",
    "chaoscontrol-net-guest",
    "-p",
    "chaoscontrol-redb-guest",
    "-p",
    "chaoscontrol-rust-workload-guest",
]
cargo_check_args = ["--lib"]
